name: Python Lint

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at 00:00 UTC
  workflow_dispatch: 

permissions: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ricardochaves/python-lint@d6ccfab90dca92e984258754d8d3cc9d963b093d # v1.4.0
